markdown:         kramdown
highlighter: rouge # 高亮显示 取值有 'rouge', 'pygments'
paginate:         5

title:            流水殇-读书强身计划
url:              http://www.lkzlee.github.com
feed:             /atom.xml
author:
    name:         lkzlee
    email:        lkzlee@gmail.com
description:      "用对方法才有效率，做对事情才有效果"

about: 			  "爱技术，爱分享，爱生活"
follow:
    github:       https://github.com/lkzlee
#    twitter:      http://www.twitter.com/piznlin
description:      "借用别人的主题还不错"

baseurl: "" 
style: 			  /css/style.css
style_highlighter:	/css/highlighter.css
blogName: 		  静水流深
blogDesc: 		  总结，积累，分享，成长.