markdown:         kramdown

toc_levels: 2..3
# 多说评论系统
comments :
    provider : duoshuo
    duoshuo : lkzlee
    short_name : lkzlee

highlighter: rouge # 高亮显示 取值有 'rouge', 'pygments'
# 关闭安全模式，以便 Jekyll 解析时会运行插件
safe: false
paginate:         5

title:            凤翔壹天子-读书强身计划
url:              http://www.lkzlee.github.com
feed:             /atom.xml
author:
    name:         lkzlee
    email:        lkzleexj@163.com
description:      "用对方法才有效率，做对事情才有效果"
encoding: utf-8
about: 			  "爱技术，爱分享，爱生活"
follow:
    github:       https://github.com/lkzlee
#    twitter:      http://www.twitter.com/piznlin
description:      "借用别人的主题还不错"

baseurl: "" 
style: 			  /css/style.css
style_highlighter:	/css/highlighter.css
blogName: 		  凤翔壹天子
blogDesc: 		  总结，积累，分享，成长.

gems: [jekyll-paginate]