# Site settings
title: 流水殇-读书强身计划
email: lkzleexj@163.com
description: > # this means to ignore newlines until "baseurl:"
  用对方法才有效率，做对事情才有效果
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lkzlee.github.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
highlighter:      rouge
kramdown:
  syntax_highlighter: rouge
sass:
  style: compressed
gems:
  - jekyll-sitemap
