# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            路飞-远
tagline:          'test'
description:      '用对方法才有效率，做对事情才有效果'
url:              https://lkzlee.github.io
baseurl:          /
encoding:		  utf-8

author:
  name:           'lkzlee路飞'
  url:            https://lkzlee.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lkzlee

gems: [jekyll-paginate]